# Generated by Django 2.0 on 2020-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=25)),
                ('sub', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
